#!/bin/bash
#
# 1er parámetro: nombre del repositorio de los dotfiles
# 2o parámetro: ruta de la clave ssh de GitHub
#

echo '🔄 >> Actualizamos el repositorio apt' 
sudo apt update -y

echo '✅ >> Actualizmos los paquetes actuales' 
sudo apt upgrade -y

echo '>'
echo '📂 > Vamos con los dotfiles' 

export DOTFILES_PATH="$HOME/.dotfiles"

# Cargamos la clave ssh de GitHub
echo '🔑 >> Cargando clave SSH...'
eval "$(ssh-agent -s)"
ssh-add "$2"

# Clonamos el repositorio indicado para los dotfiles 
echo ' Cloning...'
git clone git@github.com:kreikol/$1.git $DOTFILES_PATH

cd $DOTFILES_PATH

git submodule update --init --recursive 

export DOTLY_INSTALLER=true
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"

echo '🚀 > Go to install dotly'

$DOTLY_PATH/bin/dot package add docpars
$DOTLY_PATH/bin/dot self install

echo '>'
read -p "Restauración terminada, presione una tecla para reiniciar.."

